//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleMaker.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyLoad
    {
        public int subject_id { get; set; }
        public int syllabus_id { get; set; }
        public int quarter { get; set; }
        public int lessons_count { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Syllabi Syllabi { get; set; }
    }
}
