//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleMaker.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syllabi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Syllabi()
        {
            this.StudyLoad = new HashSet<StudyLoad>();
        }
    
        public int syllabus_id { get; set; }
        public string description { get; set; }
        public int year { get; set; }
        public Nullable<System.DateTime> date_of_creation { get; set; }
    
        public virtual CreatorsOfSyllabi CreatorsOfSyllabi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyLoad> StudyLoad { get; set; }
    }
}
